#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.2.0.{build}

# version suffix, if any (e.g. '-RC1', '-beta' otherwise '')
environment:
  version_suffix: ''

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# enable patching of Directory.Build.props
dotnet_csproj:
  patch: true
  file: '**\GitExtensions.SVN.csproj'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}$(version_suffix)'
  package_version: '{version}$(version_suffix)'

#---------------------------------#
#       build configuration       #
#---------------------------------#

# scripts to run before build
before_build:
- ps: nuget restore .\GitExtensions.SVN.sln

# build configuration
configuration: Release

build:
  # enable MSBuild parallel builds
  parallel: true
  # MSBuild verbosity level
  verbosity: minimal

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: '**\GitExtensions.SVN.*.nupkg'
